onEnableMessage: "KetheriumTools activated !"
onDisableMessage: "KetheriumTools desactivated !"
reloadMessage: "&aKetheriumTools reloaded !"

jobsAutojoin: true
jobsJoinMessage: "&aVous avez rejoins un métier !"

jobs:
  - "miner"
  - "hunter"
  - "farmer"
  - "woodcutter"
  - "fisherman"

rewardSuccess: "Récompense ajoutée avec succès."
rewardFailed: "Vous avez déjà récupéré cette récompense."

Ranks:
  rank1:
    char: ""
    name: "admin"
    gift: 500


jobsProgressBar:
  size: 20
  validChar: 'ㅊ'
  invalidChar: '╝'
