main: fr.yxoo.KetheriumTools
name: KetheriumTools
version: 1.0
author: Yxoo
api-version: 1.21
softdepend: [PlaceholderAPI]

commands:
  kethertools:
    description: Commande principale de KetheriumTools
    usage: /kethertools <reload|placeholders|reward>
    permission: kethertools.admin
    aliases: [kether]

permissions:
  kethertools.admin:
    description: Permet d'utiliser les commandes administrateur du plugin
    default: op